// Generated by CoffeeScript 1.4.0
(function() {
  var add_items, append_feed, items, store_items, title;

  title = "";

  items = [];

  add_items = function(feed) {
    store_items(feed);
    return append_feed();
  };

  store_items = function(feed) {
    $(".loading").remove();
    title = feed.title;
    return items = feed.items;
  };

  append_feed = function() {
    return $(document.body).html($(window.TEMPLATE['list.jade']({
      title: title,
      items: items
    })));
  };

  window.onload = function() {
    console.log('Parsing feed');
    $.getFeed({
      url: "feed.xml",
      success: add_items
    });
    $(".list li").live("click", function() {
      var item, item_title, _i, _len;
      item_title = $(this).text();
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        item = items[_i];
        if (item.title === item_title) {
          $(document.body).children().remove();
          $(document.body).append($(window.TEMPLATE['detail.jade']({
            title: item_title
          })));
          $(".content").html(item.description);
        }
      }
      return console.log(title);
    });
    return $(".navitems .back").live("click", function() {
      return append_feed();
    });
  };

}).call(this);
