#!/bin/sh

DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

NAMESPACE=window.TEMPLATE
INPUT=$1
OUTPUT_DIR=./js_compiled
FILENAME=$(basename $1)
OUTPUT=$FILENAME.js

echo $OUTPUT
echo "" > $OUTPUT_DIR/$OUTPUT
echo "(function(){ $NAMESPACE = $NAMESPACE || {};" >> $OUTPUT_DIR/$OUTPUT
jade -c < $INPUT >> $OUTPUT_DIR/$OUTPUT
echo "$NAMESPACE['$FILENAME'] = anonymous;})();" >> $OUTPUT_DIR/$OUTPUT
